spring:
  application:
    name: spring-ai-rag
  ai:
#    azure:
#      openai:
#        api-key: ${AZURE_OPENAI_API_KEY}
#        endpoint: ${AZURE_OPENAI_ENDPOINT}
#        chat:
#          options:
#            model: gpt-35-turbo
#        embedding:
#          enabled: false
    ollama:
      init:
        embedding:
          include: true
        pull-model-strategy: always
        timeout: 5m
        max-retries: 1
      embedding:
        additional-models:
          - mxbai-embed-large
          - nomic-embed-text
      chat:
        enabled: true
        model: mistral


file:
  vector:
    vectorStorePath:  ${SZ_DESKTOP}\Tutorials\Spring\AI\spring-ai-rag\src\main\resources\vectorstore.json
    documentsToLoad:
      - ${SZ_DESKTOP}\Tutorials\Spring\AI\spring-ai-rag\src\main\resources\data
server:
  port: 8181